import localFont from "next/font/local";
import "./../styles/globals.css";

const geistSans = localFont({
  src: "./../assets/fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./../assets/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <nav className="flex gap-4 p-4 justify-center text-sm sm:text-base sm:gap-8 font-[family-name:var(--font-geist-sans)]">
        <a href="/" className="font-bold">Home</a>
        <a href="/about">About</a>
        <a href="/contact">Contact</a>
      </nav>
        {children}
      </body>
    </html>
  );
}
